source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Dkit_Dragdrop_Example', :exclusive => true do
  pod "Dkit_Dragdrop", :path => "../"
end

target 'Dkit_Dragdrop_Tests', :exclusive => true do
  pod "Dkit_Dragdrop", :path => "../"

  
end
